Repository Youth-Developer/Sprint-Server, pull requests merged in 2021-12, with the labels that each got.

#43 :bug: (main.ts) hoisting GlobalPrefix
  src/main.ts
Labels: 🧙🏻‍♂️ youhyun, ⚡️ Simple, 🙆🏻‍♂️ Done

#40 Feature/login
  ormconfig.ts
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/token.dto.ts
  src/auth/guards/jwt-auth.guard.ts
  src/auth/interfaces/jwt-payload.ts
  src/auth/strategies/jwt.strategy.ts
  src/entities/answer-photo.entity.ts
  src/entities/answer.entity.ts
  src/entities/category.entity.ts
  src/entities/index.ts
  src/entities/question-photo.entity.ts
  src/entities/question.entity.ts
  src/entities/user.entity.ts
  src/token/token.service.ts
  src/user/dto/register.dto.ts
  src/user/dto/sign-in.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: 🙋🏻‍♂️ Review Confirm, 🧙🏻‍♂️ youhyun

#47 Feature/token
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/guards/jwt-auth.guard.ts
  src/auth/guards/local-auth.guard.ts
  src/auth/strategies/jwt.strategy.ts
  src/auth/strategies/local.strategy.ts
  src/common/decorators/user.decorator.ts
  src/common/interfaces/jwt-payload.ts
  src/token/dto/token.dto.ts
  src/token/token.service.ts
Labels: 🧙🏻‍♂️ youhyun, 🙆🏻‍♂️ Done

#46 Feature/swagger/header config
  src/main.ts
  src/user/user.controller.ts
Labels: 🧙🏻‍♂️ youhyun, 🙆🏻‍♂️ Done

#49 :sparkles: (entity) entity column name config
  src/entities/answer.entity.ts
  src/entities/category.entity.ts
  src/entities/question.entity.ts
  src/entities/user.entity.ts
Labels: 🧙🏻‍♂️ hyunin, ⚡️ Simple, 🙆🏻‍♂️ Done

#51 Feature/exception/token
  src/auth/guards/jwt-auth.guard.ts
Labels: 🧙🏻‍♂️ youhyun, ⚡️ Simple, 🙆🏻‍♂️ Done

#53 Hotfix/register
  src/auth/auth.service.ts
  src/auth/strategies/local.strategy.ts
Labels: 👩🏻‍🚒 Hotfix, 👀 In Review, 🧙🏻‍♂️ hyunin, ⚡️ Simple

#54 feature/modify-entity
  src/entities/question.entity.ts
Labels: 👀 In Review, 🧙🏻‍♂️ hyunin, ⚡️ Simple
